export { default as Header } from './Header'
export { default as HeroSection } from './HeroSection'
export { default as StatsSection } from './StatsSection'
export { default as IntegratedMarketsSection } from './IntegratedMarketsSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as CTASection } from './CTASection'
export { default as Footer } from './Footer' 