import { Activity } from "./types"

export const activitiesData: Activity[] = [
    {
        id: "1",
        action: "Yield Optimized",
        protocol: "MORPHO → SEAMLESS",
        amount: "+$234.50",
        time: "2 minutes ago",
        type: "optimization",
        txHash: "0x1234...5678",
        status: "completed",
    },
    {
        id: "2",
        action: "Deposit",
        protocol: "USDC",
        amount: "$5,000.00",
        time: "1 hour ago",
        type: "deposit",
        txHash: "0x2345...6789",
        status: "completed",
    },
    {
        id: "3",
        action: "Yield Earned",
        protocol: "SEAMLESS",
        amount: "+$89.23",
        time: "3 hours ago",
        type: "earning",
        txHash: "0x3456...7890",
        status: "completed",
    },
    {
        id: "4",
        action: "Rebalanced",
        protocol: "Portfolio",
        amount: "$12,450.00",
        time: "6 hours ago",
        type: "rebalance",
        txHash: "0x4567...8901",
        status: "completed",
    },
    {
        id: "5",
        action: "Withdraw",
        protocol: "AAVE",
        amount: "$2,500.00",
        time: "12 hours ago",
        type: "withdraw",
        txHash: "0x5678...9012",
        status: "completed",
    },
    {
        id: "6",
        action: "Yield Optimized",
        protocol: "EULER → MORPHO",
        amount: "+$156.78",
        time: "1 day ago",
        type: "optimization",
        txHash: "0x6789...0123",
        status: "completed",
    },
    {
        id: "7",
        action: "Deposit",
        protocol: "ETH",
        amount: "$8,750.00",
        time: "2 days ago",
        type: "deposit",
        txHash: "0x7890...1234",
        status: "completed",
    },
    {
        id: "8",
        action: "Yield Earned",
        protocol: "COMPOUND",
        amount: "+$67.45",
        time: "2 days ago",
        type: "earning",
        txHash: "0x8901...2345",
        status: "completed",
    },
    {
        id: "9",
        action: "Rebalanced",
        protocol: "Portfolio",
        amount: "$18,900.00",
        time: "3 days ago",
        type: "rebalance",
        txHash: "0x9012...3456",
        status: "completed",
    },
    {
        id: "10",
        action: "Yield Optimized",
        protocol: "VENUS → MOONWELL",
        amount: "+$298.34",
        time: "4 days ago",
        type: "optimization",
        txHash: "0x0123...4567",
        status: "completed",
    },
] 