import { Market } from "./types"

export const marketsData: Market[] = [
    {
        id: "usdc-morpho",
        asset: "USDC",
        protocol: "MORPHO",
        apy: "7.67%",
        tvl: "$2.4B",
        liquidity: "$450M",
        trend: "up",
        change24h: "+0.23%",
        risk: "Low",
        category: "Lending",
        chain: "Ethereum",
        featured: true,
    },
    {
        id: "eth-seamless",
        asset: "ETH",
        protocol: "SEAMLESS",
        apy: "9.13%",
        tvl: "$1.8B",
        liquidity: "$320M",
        trend: "up",
        change24h: "+0.45%",
        risk: "Medium",
        category: "Lending",
        chain: "Base",
        featured: false,
    },
    {
        id: "usdt-aave",
        asset: "USDT",
        protocol: "AAVE",
        apy: "3.57%",
        tvl: "$5.2B",
        liquidity: "$890M",
        trend: "down",
        change24h: "-0.12%",
        risk: "Low",
        category: "Lending",
        chain: "Ethereum",
        featured: true,
    },
    {
        id: "dai-euler",
        asset: "DAI",
        protocol: "EULER",
        apy: "6.39%",
        tvl: "$980M",
        liquidity: "$180M",
        trend: "up",
        change24h: "+0.18%",
        risk: "Medium",
        category: "Lending",
        chain: "Ethereum",
        featured: false,
    },
    {
        id: "wbtc-compound",
        asset: "WBTC",
        protocol: "COMPOUND",
        apy: "4.82%",
        tvl: "$3.1B",
        liquidity: "$520M",
        trend: "up",
        change24h: "+0.08%",
        risk: "Low",
        category: "Lending",
        chain: "Ethereum",
        featured: false,
    },
    {
        id: "usdc-moonwell",
        asset: "USDC",
        protocol: "MOONWELL",
        apy: "8.24%",
        tvl: "$650M",
        liquidity: "$120M",
        trend: "up",
        change24h: "+0.31%",
        risk: "Medium",
        category: "Lending",
        chain: "Base",
        featured: false,
    },
    {
        id: "arb-radiant",
        asset: "ARB",
        protocol: "RADIANT",
        apy: "11.45%",
        tvl: "$420M",
        liquidity: "$85M",
        trend: "down",
        change24h: "-0.67%",
        risk: "High",
        category: "Lending",
        chain: "Arbitrum",
        featured: false,
    },
    {
        id: "bnb-venus",
        asset: "BNB",
        protocol: "VENUS",
        apy: "5.67%",
        tvl: "$1.2B",
        liquidity: "$240M",
        trend: "up",
        change24h: "+0.15%",
        risk: "Medium",
        category: "Lending",
        chain: "BSC",
        featured: false,
    },
] 